# Generated by Django 3.0.2 on 2020-02-11 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MasterApp', '0002_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Lead_Title', models.CharField(blank=True, max_length=200, null=True)),
                ('Contacted_Person', models.CharField(blank=True, max_length=200, null=True)),
                ('Phone', models.IntegerField()),
                ('Purpose', models.CharField(blank=True, max_length=200, null=True)),
                ('Priority', models.CharField(blank=True, max_length=200, null=True)),
                ('Annual_Revenue', models.IntegerField()),
                ('Description', models.CharField(blank=True, max_length=200, null=True)),
                ('Date', models.DateField()),
                ('Email', models.EmailField(max_length=254)),
                ('Lead_Status', models.CharField(blank=True, max_length=200, null=True)),
                ('Sales_Employee', models.CharField(blank=True, max_length=200, null=True)),
                ('Lead_Source', models.CharField(blank=True, max_length=200, null=True)),
                ('Industry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='industry', to='MasterApp.Organisation')),
                ('Mobile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mobile', to='MasterApp.Organisation')),
                ('Owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='MasterApp.Organisation')),
            ],
        ),
    ]
