# Generated by Django 3.0.2 on 2020-02-11 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MasterApp', '0003_lead'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='Industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leadindustry', to='MasterApp.Industry'),
        ),
    ]
