# Generated by Django 3.0.2 on 2020-02-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MasterApp', '0004_auto_20200211_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='Annual_Revenue',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='Date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='Email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lead',
            name='Phone',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
